### ISSUE TITLE
Interested Collaborator - Vishesh Gupta

### ISSUE THREAD

**Issue by Vishesh-Gupta** [WorldHealthOrganization/open-source-communication-channel#17]
## About
This template is for interested expert individuals, companies, organizations or communities that wish to collaborate on forthcoming open source software from the World Health Organization. Individuals and entities that already have collaborations or partnerships with WHO may use existing communication channels in lieu of this submission. **Kindly note this repository is public and any information submitted on this Issue will be as well. WHO is not responsible for sensitive information submitted.** 

WHO will be in touch with interested collaborators as opportunities arise.

### About You
**1. I am submitting on behalf of (select all that apply):**
- [x] Myself (as an individual)
- [ ] My company, government or organization
- [ ] My open source community

**2. What is your name:** Vishesh Gupta

**3. If applicable, please type the name of the company, government, organization or open source community on behalf of which you're submitting:** Open Source Community

**4. Please type your GitHub ID:** vishesh-gupta

**5. Can we contact you at your GitHub ID with updates on WHO open source projects?** Your information will not be shared further or for any other purpose.
- [x] Yes
- [ ] No

### About Your Interest
**6. Please consult the [ReadMe](https://github.com/WorldHealthOrganization/open-source-communication-channel) and indicate the projects on which you're interested in collaborating:**

- [ ] Augmented Public Health Intelligence - AI/ML
- [x] Semantic Web of Public Health Data - open APIs
- [ ] Active COVID-19 Surveillance Data Access Layer
- [x] Go.Data
- [ ] Other: _please enter a description_

**7. Please briefly describe how you would like to collaborate on the project(s) above:** 
Anything Fullstack in any language and anything infrastructure related

**Comment by smbuthia** [comment]
We have now [formalized the WHO Open Source Programme Office](https://github.com/WorldHealthOrganization/open-source-communication-channel/discussions/30#discussioncomment-3838124).  

We are supporting project maintainers to revise contribution guidelines for individual projects to ensure adoption of standard open source best practices. We will therefore be updating the [list of open source projects](https://github.com/WorldHealthOrganization/open-source-communication-channel#current-projects) with links to project repositories and at least one point of contact each that you can reach out to. 

**We are therefore retiring the *Interested Collaborator* issue template and closing existing *Interested Collaborator* issues to create a new streamlined and responsive process. If you see a project on [this list](https://github.com/WorldHealthOrganization/open-source-communication-channel#current-projects) you would like to collaborate on, follow the link to the repository and read the contribution guidelines for the project.**

In case you would like to collaborate in a project that you understand to be open source but is not listed, please start [a new discussion](https://github.com/WorldHealthOrganization/open-source-communication-channel/discussions/new?category=open-source-programme-office) and we will respond with the appropriate guidance.
