### ISSUE TITLE
Would be Taiwan able to contribute?

### ISSUE THREAD

**Issue by tonyhhyip** [WorldHealthOrganization/open-source-communication-channel#18]
Since WHO is refusing the contribution or joining of Taiwan government, would Taiwan contributor allow to contribute in WHO open source project?

**Comment by milovanovicdusan** [comment]
@tonyhhyip - thank you very much for your interest! In the spirit of open-source software and good faith, we are welcoming and encouraging any individual, organisation and community of any size to work with us on sharing knowledge and developing solutions for improving health and well-being of each and every person worldwide. We are looking forward to a fruitful collaboration for the benefit of humanity. You and anyone else from Taiwan, as well as any other part of the World, are more than welcome.
