### ISSUE TITLE
Interested Collaborator - Mekom Solutions (→ Ozone HIS → OpenMRS 3)

### ISSUE THREAD

**Issue by mks-d** [WorldHealthOrganization/open-source-communication-channel#35]
### About You
**1. I am submitting on behalf of:**
- [ ] Myself (as an individual)
- [x] My company, government or organization
- [x] My open source community

**2. What is your name:** Dimitri RENAULT

**3. If applicable, please type the name of the company, government, organization or open source community on behalf of which you're submitting:**

[**Mekom Solutions**](https://github.com/mekomsolutions)
&nbsp;&nbsp; ↳ [Ozone HIS](https://github.com/ozone-his/ozone-docker/#readme)
&nbsp;&nbsp;&nbsp;&nbsp; ↳ [**OpenMRS 3**](https://wiki.openmrs.org/x/pQFiDQ)

**4. Please type your GitHub ID:** [@mks-d](https://github.com/mks-d)

**5. Can we contact you at your GitHub ID with updates on WHO open source projects?** Your information will not be shared further or for any other purpose.
- [x] Yes
- [ ] No

### About Your Interest
**6. Please consult the [ReadMe](https://github.com/WorldHealthOrganization/open-source-communication-channel) and indicate the projects on which you're interested in collaborating:**

- [ ] Augmented Public Health Intelligence - AI/ML
- [ ] Semantic Web of Public Health Data - open APIs
- [x] Active COVID-19 Surveillance Data Access Layer
- [x] Go.Data
- [x] Other: EMR/EHR and interoperable patient management software in general

**7. Please briefly describe how you would like to collaborate on the project(s) above:**

Mekom Solutions develops and **maintains** open-source patient-centric (EMR/EHR) applications made with OpenMRS 3 - the open-source EMR system for our world. We believe that open digital health is a pillar of universal access to healthcare; and we are committed to building it by **co-contributing to Digital Public Goods**, and specifically to OpenMRS 3.

Disease surveillance is already supported in OpenMRS 3 for HIV and there is no particular challenge nor impediments to extend this to COVID-19. There are a number of native features of OpenMRS 3 that can directly support contact tracing workflows, for instance the management of patient lists and [OpenMRS Offline](https://wiki.openmrs.org/x/PIAZDw). Furthermore an upcoming COVID-19 OpenMRS 3 package would combine perfectly with WHO's [DHIS2 COVID-19 Surveillance & Response Toolkit](https://dhis2.org/covid-surveillance/).

We would like to increase WHO's awareness of OpenMRS 3 by implementing and trying it in the context of disease surveillance. This endeavour shall demonstrate that its potential goes beyond that scope: OpenMRS 3 is a full-fledged EMR system that is able to support frontline health workers at the point-of-care in a wide variety of clinical areas that are of interest to the WHO. It has an extensive ecosystem of donors and contributors, an ambitious roadmap and a proven track record since it has been implemented at thousands of health facilities around the world, including at the national level in many countries.

----

A very quick peek at OpenMRS 3:
<figure>
  <figcaption>Fig.1 - OpenMRS 3, patient list for triage</figcaption>
  <img src="https://user-images.githubusercontent.com/12812196/159165970-0e0f3c53-6e49-4a63-9cfd-4a3d6a0559c1.png" width="65%">
</figure>

<figure>
  <figcaption>Fig.2 - OpenMRS 3, reviewing lab results</figcaption>
  <img src="https://user-images.githubusercontent.com/12812196/159166405-3a00e76f-b21e-48a2-8097-2e60b2163268.png" width="65%">
</figure>

**Comment by smbuthia** [comment]
We have now [formalized the WHO Open Source Programme Office](https://github.com/WorldHealthOrganization/open-source-communication-channel/discussions/30#discussioncomment-3838124).  

We are supporting project maintainers to revise contribution guidelines for individual projects to ensure adoption of standard open source best practices. We will therefore be updating the [list of open source projects](https://github.com/WorldHealthOrganization/open-source-communication-channel#current-projects) with links to project repositories and at least one point of contact each that you can reach out to. 

**We are therefore retiring the *Interested Collaborator* issue template and closing existing *Interested Collaborator* issues to create a new streamlined and responsive process. If you see a project on [this list](https://github.com/WorldHealthOrganization/open-source-communication-channel#current-projects) you would like to collaborate on, follow the link to the repository and read the contribution guidelines for the project.**

In case you would like to collaborate in a project that you understand to be open source but is not listed, please start [a new discussion](https://github.com/WorldHealthOrganization/open-source-communication-channel/discussions/new?category=open-source-programme-office) and we will respond with the appropriate guidance.
